[package]
name = "proto-did"
version = "0.1.0"
edition = "2024"

[features]
default = ["cli"]
cli = []

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
tokio = {version = "1", features = ["full"]}
url = "2.5.4"
